### ISSUE TITLE
sls alexa update failing with localSkills.find is not a function

### ISSUE THREAD

**Issue by idvorkin** [marcy-terui/serverless-alexa-skills#25]
I'm pretty sure I'm doing something wrong :) but not sure how to debug :(

```
sls alexa update
 
  Type Error ---------------------------------------------
 
  localSkills.find is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           11.4.0
     Serverless Version:     1.32.0
 
```
NOTE: I had to downgrade to serverless 1.32.0 to avoid auth errors: 
```
sls version
> 1.32.0
```

My serverless.yml is: 

```

service: sls-meetup-alexa-skill

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-alexa-skills

custom:
  alexa:
    localServerPort: 9090
    skills:
        id: amzn1.ask.skill.07bac39f-a0f3-4115-93b7-xxxxxx
        manifest:
          publishingInformation:
            locales:
              en-US:
                name: MeetupEvents
          apis:
            custom: {}
          manifestVersion: '1.0'
        models:
          en-US:
            interactionModel:
              languageModel:
                invocationName: meetup events
                intents:
                  - name: MeetupIntent
                    samples:
                    - 'my events'
                    - 'my meetup events'
                    - 'anything interesting in my meetup'
                    - 'give me all my meetup events'
                  - name: AMAZON.HelpIntent
                    samples: []
                  - name: AMAZON.CancelIntent
                    samples: []
                  - name: AMAZON.StopIntent
                    samples: []
functions:
  meetupHandler:
    handler: handler.hello
    events:
      - alexaSkill: amzn2.ask.skill.07bac39f-a0f3-4115-93b7-xxxxx
```
